### PR TITLE
Fix Auth Provider detection on using GKE, AKS

### PR DESCRIPTION
**Pull request by cactuschibre**
See: https://github.com/kubernetes/client-go/issues/242

Without explicit import, we got:

```
### VERSION ###
Error: failed loading context to initialize client: no Auth Provider found for name "azure"
```

### CODE REVIEW

**Comment by mtardy** [comment]
Hey, thanks for taking the time to create that PR! You are correct, I should have loaded all these plugins like [documented here](https://github.com/kubernetes/client-go/blob/master/examples/out-of-cluster-client-configuration/main.go#L33) and it makes sense to load them all in kdigger.

Just one question because I don't have the time to reproduce that bug by creating an Azure cluster, you had this issue while trying to communicate from outside an AKS cluster? Because I'm not sure in-cluster config would fail in this case (but would love to know).

**Comment by cactuschibre** [comment]
Yes it was outside the AKS ;) Inside no I do not think it will fail, but I could test

**Comment by mtardy** [comment]
Thanks a lot! I'll make a new release version after updating the dependencies to the k8s version!

**Comment by mtardy** [comment]
New release https://github.com/quarkslab/kdigger/releases/tag/v1.4.0 :)

**Comment by cactuschibre** [comment]
Perfect!

**Pull request merged**
